### ISSUE TITLE
Run validation script on current models and assess predictive power 

### ISSUE THREAD

**Issue by breannam** [dssg/bikeshare#31]

**Comment by jpvelez** [comment]
We ran MSE validation on the poisson model using historical data from DC, comparing our predictions at 15, 30, 45, 60, and 120min with the actual number of bikes at stations at those times. We plotted the results with nice ggplot2 histrograms.

**Note**: the model was estimated from data with rebalancing arrivals and departures removed, and compared to similarly adjusted historical station data. In other words, we're comparing our predictions of the (estimated) change due to **rider** arrivals and departures with the "actual" **rider** arrivals and departures.
