### ISSUE TITLE
Make a Historical Data API

### ISSUE THREAD

**Issue by hunterowens** [dssg/bikeshare#68]
First path:

/api/city/year/month/day

Should return 1 day worth of data.

**Comment by erinselene** [comment]
Hi,

I'm also interested in using your aggregated historical data. I saw in your other thread that you linked to a subset of DC data in S3. Since it looks like your API isn't done, do you possibly have links to the other S3 data? I'm interested in DC, New York, Chicago, and Boston. I'm also curious whether your scraper continued to update the data after the project was done. 

Thank you!

Erin

**Comment by hunterowens** [comment]
@erinselene: Alas, we've since discontinued the scrapers/db. I'm pretty sure that @stevevance or @iandees has historical Chicago data, and @noneck should have NYC. Talk to @harlanh about DC.

**Comment by iandees** [comment]
My scraper thing has been grabbing 5-minutely data from Divvy for at least
a year or two. Happy to share that somewhere.

**Comment by stevevance** [comment]
@iandees I could add you as a contributor to [divvy-munging](https://github.com/stevevance/divvy-munging), where I put pre-calculated data for Divvy Data Challenge entrants.
